package com.ngocvu.example.utils


object BundleKeys {
    const val flowType = "FLOW_TYPE"
    const val viewType = "VIEW_TYPE"
    const val webType = "WEB_TYPE"
    const val success = "SUCCESS"
    const val failed = "FAILED"
    const val selectedQuestion = "SELECTED_QUESTION"
    const val mobileNo = "MOBILE_NO"
    const val merchants = "MERCHANTS"
    const val category = "CATEGORY"
    const val voucherId = "VOUCHER_ID"
    const val poolId = "POOL_ID"
    const val voucherType = "VOUCHER_TYPE"
    const val voucherName = "VOUCHER_NAME"
    const val filterCategory = "FILTER_CATEGORY"
    const val imageUrl = "IMAGE_URL"
    const val merchantName = "MERCHANT_NAME"
    const val about = "ABOUT"
    const val iconUrl = "ICON_URL"
    const val creditCard = "CREDIT_CARD"
    const val title = "TITLE"
    const val email = "EMAIL"
    const val nric = "NRIC"
    const val passport = "PASSPORT"
    const val blCard = "BL_CARD"
    const val hasInstantCard = "HAS_INSTANT_CARD"
    const val hasMultipleCard = "HAS_MULTIPLE_CARD"
    const val hasOldPin = "HAS_OLD_PIN"
    const val totalCard = "TOTAL_CARD"
    const val screenNumber = "SCREEN_NAME"
    const val myVoucher = "MY_VOUCHER"
    const val transactionType = "TRANSACTION_TYPE"
    const val transactionId = "TRANSACTION_ID"
    const val recipients = "RECIPIENTS"
    const val collectedPointsTransaction = "COLLECTED_POINTS_TRANSACTION"
    const val usedPointsTransaction = "USED_POINTS_TRANSACTION"
    const val creditCardId = "CREDIT_CARD_ID"
    const val merchantId = "MERCHANT_ID"
    const val outletId = "OUTLET_ID"
    const val isKeyInAmount = "IS_KEY_IN_AMOUNT"
    const val paymentUrl = "PAYMENT_URL"
    const val scanMerchant = "SCAN_MERCHANT"
    const val merchantTransaction = "MERCHANT_TRANSACTION"
    const val vouchers = "VOUCHERS"
    const val trxId = "trxId" // Transaction Id
    const val trxType = "trxType" // Transaction Type

    const val isProfileFlow = "IS_PROFILE_FLOW"
    const val isPartnerLink = "IS_PARTNER_LINK"

    const val LIST_OF_EXPIRATION = "LIST_OF_EXPIRATIONS"
    const val profileData = "PROFILE_DATA"
    const val addresses = "ADDRESSES"
    const val address = "ADDRESS"
    const val deliveryAddressId = "DELIVERY_ADDRESS_ID"
    const val addressesPosition = "ADDITIONAL_ADDRESS_POSITION"

    const val POINT_TRANSACTION_TAB = "POINT_TRANSACTION_TYPE"
    const val language = "LANGUAGE"
    const val gender = "GENDER"
    const val race = "RACE"
    const val date = "DATE"
    const val maritalStatus = "MARITAL_STATUS"
    const val occupation = "OCCUPATION"
    const val dob = "DOB"
    const val WALLET_TRANSACTION_TAB = "WALLET_TRANSACTION_TYPE"
    const val GIFT_TAB = "GIFT_TAB"

    const val voucherTransaction = "VOUCHER_TRANSACTION"
    const val cashbackTransaction = "CASHBACK_TRANSACTION"
    const val transaction = "TRANSACTION"


    const val generalQuestions = "GENERAL_QUESTIONS"
    const val participatingOutlets = "PARTICIPATING_OUTLETS"
    const val promotions = "PROMOTIONS"
    const val GIFT_QR_CODE = "GIFT_QR_CODE"
    const val GIFT_SHARES = "GIFT_SHARES"
    const val VOUCHER_NUMBER = "VOUCHER_NUMBER"
    const val VOUCHER_QR_CODE = "VOUCHER_QR_CODE"
    const val URL = "URL"

    const val NOTIFICATION_TYPE = "NOTIFICATION_TYPE"
    const val NOTIFICATION_ID = "NOTIFICATION_ID"
    const val NOTIFICATION_DATA = "NOTIFICATION_DATA"

    const val questionId = "QUESTION_ID"
    const val paymentDetails = "PAYMENT_DETAILS"
    const val qrCode = "QR_CODE"
    const val barCode = "BAR_CODE"

    const val Issue = "Issue"

}